language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_SECRET
    - secure: TRK13faoxuV2rr47Cmre7p4yJiqe9ubmf8aGUAf4FP8lvxqPnWYRITIK4FV2znb6KBbmKhUVRQCZ9tTDd6a8j7iurXq0Z4VDgH4Z1qm4MsmUHCSAPrPwbQ86lqVW2ojjWlnoainR3QXjEzemrL/w8rqVBymGfwgjQmi2r01F/oSyueWg2hbHv3UKUWBHuxC00KBFwEBQnCH1GC3AuQIX1OIcS8uizbHj1pYwcKnISZtLM/5TXjNQ+sRV4jxrE132ItvqsRN5tGurPbCnwvgtDjyoduBhWCiqTaTrPaX0n/zhs6pliUQMKfDd8tKXnYwAbly0pD039yXkVvx3EbzXQE2GfCYuSXjaqePYLOMbKRVbUEyhUc5ea8pBW/WAVma84DnPq0rlj4Hch/ZD1rDS9tOtIIXeDcTNsK7zqUDZckR2ZuG7oJD9BJ3stZK595kNkArp1NAXth2Zm//CiqvHHxcCkkM2W44BviZxOtN+t+/OyZ+tw215s8djIeeADC7TonbvZmm7LIdFllsQHeK5th1XRk5PRY6VcFTL5KDs5Ioolws+SF2kOm2CVzndYYBd+G6Hw8Ep0evt6zb8UuT1nXeBSkJw0DqiwGyCqJUPwe6HaUsPSMpP4myjYLVSETvY59YskKeEGoB8Y5QaXBYHYnkZuPL4LFPXr+2Z2tikpVo=
    # FIREBASE_TOKEN
    - secure: MZeJehCvEYF7GLFEtSS0uEzJhd0/Cp+lJVTuZcHxgCsn1DeNqkVWmBoAdGBK29ALLDYaka/+UA3e/aZ3E4JNySy6V0eKF1E8z9SEGfKqUfqMJd87hmqIW05KN4WgdBdZ3EfitRjdEEfPKSIIZWrzkl1fimAjX5Bb2e7adpwd4f1kgkHC8Gaw5iV373x3scbSlTY+2JfiT/4jvYg0Aw9uYH/2h784aCj1vmvAoxaYcyZ21NaEH7Ok5DUhy9qNmorrWnwEmMpGiolnmZaSgwHyurnBG60HJlIN2EEpnMRznLkvz0JN2eV2I2/Jdroo7ESin6bBOoWc+VAAu48YTCpxrYufg0sgbyZYtS7Tdlc/ascNHJjYdPg7bctGyXxIGmeSLMlQ40ex3CQwqlj8gGY7i2D341s/gq1xUUE5xGVjEDbZ2ipcHhts02fk+rI6X84FXSJAF+WUb5VaZ2KMbXbts5YCJFL3azwCmKvcjpLMoxz/ObyAjiUNzMKvaI2yyxcHRiGVJumZ/i5K5Y9Q02VXpCj3gFb8bzjIUT/vIg0nxD0L5TXcrYYc3Hf2kFmNyIQ6E7uCYdE68tKrCMp2AXZ4Pbnm29pVJmAeM7TP2IzwJoSiGyohWJ8Yt3df9IQz9uwstJ9vQJCRIsBVVmKL1vEtd0ahD/Pm4fQ05+7pEP6Fj3A=
